#ifndef IALGORITHMFACTORY_GLOBAL_H
#define IALGORITHMFACTORY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(IALGORITHMFACTORY_LIBRARY)
#  define IALGORITHMFACTORYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define IALGORITHMFACTORYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // IALGORITHMFACTORY_GLOBAL_H
