#ifndef IDEVICEFACTORY_GLOBAL_H
#define IDEVICEFACTORY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(IDEVICEFACTORY_LIBRARY)
#  define IDEVICEFACTORYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define IDEVICEFACTORYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // IDEVICEFACTORY_GLOBAL_H
