#ifndef PLUGINHELPER_GLOBAL_H
#define PLUGINHELPER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PLUGINHELPER_LIBRARY)
#  define PLUGINHELPERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PLUGINHELPERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PLUGINHELPER_GLOBAL_H
