#ifndef IREPOSITORYMANAGER_GLOBAL_H
#define IREPOSITORYMANAGER_GLOBAL_H

#include <QtCore/qglobal.h>

/**
#if defined(IREPOSITORYMANAGER_LIBRARY)
#  define IREPOSITORYMANAGERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define IREPOSITORYMANAGERSHARED_EXPORT Q_DECL_IMPORT
#endif
**/
#endif // IREPOSITORYMANAGER_GLOBAL_H
