#ifndef SIMPLEALGORITHM_GLOBAL_H
#define SIMPLEALGORITHM_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SIMPLEALGORITHM_LIBRARY)
#  define SIMPLEALGORITHMSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SIMPLEALGORITHMSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SIMPLEALGORITHM_GLOBAL_H
