#ifndef DEVICEPORTAL_GLOBAL_H
#define DEVICEPORTAL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DEVICEPORTAL_LIBRARY)
#  define DEVICEPORTALSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DEVICEPORTALSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DEVICEPORTAL_GLOBAL_H
