#ifndef REPOSITORYMANAGER_GLOBAL_H
#define REPOSITORYMANAGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(REPOSITORYMANAGER_LIBRARY)
#  define REPOSITORYMANAGERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define REPOSITORYMANAGERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // REPOSITORYMANAGER_GLOBAL_H
