#ifndef IREPOSITORY_GLOBAL_H
#define IREPOSITORY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(IREPOSITORY_LIBRARY)
#  define IREPOSITORYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define IREPOSITORYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // IREPOSITORY_GLOBAL_H
