#ifndef TRANCIEVERLOADER_GLOBAL_H
#define TRANCIEVERLOADER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TRANCIEVERLOADER_LIBRARY)
#  define TRANCIEVERLOADERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TRANCIEVERLOADERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TRANCIEVERLOADER_GLOBAL_H
