#ifndef SENSORPLUGINLOADER_GLOBAL_H
#define SENSORPLUGINLOADER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SENSORPLUGINLOADER_LIBRARY)
#  define SENSORPLUGINLOADERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SENSORPLUGINLOADERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SENSORPLUGINLOADER_GLOBAL_H
