#ifndef CONTROLHARDWAREMANAGER_GLOBAL_H
#define CONTROLHARDWAREMANAGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CONTROLHARDWAREMANAGER_LIBRARY)
#  define CONTROLHARDWAREMANAGERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CONTROLHARDWAREMANAGERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CONTROLHARDWAREMANAGER_GLOBAL_H
