#ifndef ALGORITHMLOADER_GLOBAL_H
#define ALGORITHMLOADER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ALGORITHMLOADER_LIBRARY)
#  define ALGORITHMLOADERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ALGORITHMLOADERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ALGORITHMLOADER_GLOBAL_H
