#ifndef DEVICEMANAGER_GLOBAL_H
#define DEVICEMANAGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DEVICEMANAGER_LIBRARY)
#  define DEVICEMANAGERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DEVICEMANAGERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DEVICEMANAGER_GLOBAL_H
